"""Layer A arithmetic anchors. Hand-built cases, no fixtures on disk.

No real identity number appears here. The Aadhaar numbers are generated by
appending a computed Verhoeff digit to an arbitrary eleven-digit payload, so
they are checksum-valid and belong to nobody.
"""
import pytest

from modules.validation.checksums import (
    check_aadhaar, check_dl, check_epic, check_pan, verhoeff, verhoeff_digit,
)


def aadhaar(payload_11: str) -> str:
    return payload_11 + verhoeff_digit(payload_11)


# ------------------------------------------------------------------ Verhoeff

def test_generated_aadhaar_numbers_verify():
    for payload in ("23456789012", "99887766554", "40000000000"):
        assert verhoeff(aadhaar(payload)), payload


def test_single_digit_change_is_caught():
    number = aadhaar("23456789012")
    for i in range(len(number)):
        for d in "0123456789":
            if d == number[i]:
                continue
            assert not verhoeff(number[:i] + d + number[i + 1:])


def test_adjacent_transposition_is_caught():
    # This is what Verhoeff buys over a modulus-10 sum: it catches the two most
    # common human errors, a single wrong digit and a swapped pair.
    number = aadhaar("23456789012")
    swapped = 0
    for i in range(len(number) - 1):
        if number[i] == number[i + 1]:
            continue
        t = number[:i] + number[i + 1] + number[i] + number[i + 2:]
        assert not verhoeff(t)
        swapped += 1
    assert swapped > 0


def test_aadhaar_rejects_wrong_length_and_leading_zero_or_one():
    ok, detail = check_aadhaar("12345")
    assert not ok and "12" in detail
    assert not check_aadhaar(aadhaar("01234567890"))[0]
    assert not check_aadhaar(aadhaar("11234567890"))[0]


def test_aadhaar_accepts_spaced_formatting():
    n = aadhaar("23456789012")
    spaced = f"{n[:4]} {n[4:8]} {n[8:]}"
    assert check_aadhaar(spaced)[0]


# ----------------------------------------------------------------------- PAN

def test_pan_format_and_holder_type():
    ok, detail = check_pan("ABLPG7040F")
    assert ok
    assert "individual" in detail


def test_pan_rejects_malformed_and_unknown_holder_type():
    assert not check_pan("ABL7G7040F")[0]
    assert not check_pan("ABLPG7040")[0]
    assert not check_pan("ABLXG7040F")[0]     # X is not a holder category


def test_pan_fifth_character_must_match_the_surname():
    # The genuine cross-field constraint, and the one a spliced name breaks.
    assert check_pan("ABLPG7040F", surname="Gharat")[0]
    ok, detail = check_pan("ABLPG7040F", surname="Sharma")
    assert not ok
    assert "SHARMA" in detail


def test_pan_format_alone_passes_an_obviously_fake_number():
    # Documents the ceiling: there is no published PAN check character, so
    # structure is all we have and we must not imply more.
    assert check_pan("AAAPA0000A")[0]


# ------------------------------------------------------------------ Voter ID

def test_epic_format():
    assert check_epic("ABC1234567")[0]
    assert not check_epic("AB1234567")[0]
    assert not check_epic("ABC123456")[0]
    assert not check_epic("ABCD123456")[0]


# ----------------------------------------------------------- Driving licence

def test_dl_state_and_rto():
    ok, detail = check_dl("MH12 2019 0001234")
    assert ok
    assert "Maharashtra" in detail and "12" in detail


def test_dl_rejects_unknown_state_and_impossible_year():
    assert not check_dl("XX1220190001234")[0]
    assert not check_dl("MH1229990001234")[0]
    assert not check_dl("MH0020190001234")[0]


@pytest.mark.parametrize("value", ["MH-12-2019-0001234", "MH1220190001234"])
def test_dl_accepts_both_printed_separators(value):
    assert check_dl(value)[0]
