"""The synthetic document generator. BUILD TIME ONLY.

    from data.generator import build
    doc = build("aadhaar", seed=7, sign=True)

`CLAUDE.md` rule 4 has always said *"Everything is generated by
`data/generator/`"* as a statement of fact. Until now it was a statement of
intent: the tamper module was measured on scraped Roboflow imagery, which is
exactly the "where did your training data come from?" question `DEMO.md`
predicts a panel will ask.

One call produces a document, its labels, and - when asked - a real Ed25519
signature over its payload, minted by the reference issuer. Nothing here is
importable from the screening path; `issuer/` may be called from `data/`
precisely because this is out-of-band tooling and not inspection (rule 7).

The seed is the whole contract. Same seed, same person, same card, same
numbers - so a test can regenerate the exact document it asserts about, and so
an Aadhaar and a PAN built from one seed agree with each other by construction.
`disagree_on()` is then a single deliberate edit, which is what Scene 3 needs.
"""
import sys
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from data.generator import render as _render                        # noqa: E402
from data.generator.identity import Identity                        # noqa: E402
from data.generator.identity import build as build_identity         # noqa: E402

DOC_TYPES = ("passport", "aadhaar", "pan", "voter_id", "dl", "visa")

#: Where the reference issuer keeps the keys `issuer/cli.py init` wrote.
#: `Keypair.load` takes the directory, not the file.
ISSUER_DIR = ROOT / "var" / "issuer"
KEY_PATH = ISSUER_DIR / "SIH-REF-01.key"


@dataclass
class GeneratedDoc:
    """One synthetic document and everything known about it."""
    doc_type: str
    identity: Identity
    image: np.ndarray                     # BGR, ready for cv2 / the pipeline
    labels: list = field(default_factory=list)   # [(class, x1, y1, x2, y2)] px
    values: dict = field(default_factory=dict)   # what was actually printed
    payload: dict = field(default_factory=dict)  # the canonical signed fields
    envelope: str | None = None                  # the signed envelope, if signed

    @property
    def size(self) -> tuple[int, int]:
        h, w = self.image.shape[:2]
        return w, h

    def yolo_labels(self, ontology: tuple[str, ...] = _render.ONTOLOGY) -> list[str]:
        """YOLO lines: `class_index cx cy w h`, all normalised.

        This is the payoff for rendering rather than vectorising - the labels
        are a by-product of having drawn the thing, not a second job.
        """
        w, h = self.size
        lines = []
        for name, x1, y1, x2, y2 in self.labels:
            if name not in ontology:
                continue
            x1, y1 = max(0, x1), max(0, y1)
            x2, y2 = min(w, x2), min(h, y2)
            if x2 <= x1 or y2 <= y1:
                continue
            lines.append(
                f"{ontology.index(name)} {((x1 + x2) / 2) / w:.6f} "
                f"{((y1 + y2) / 2) / h:.6f} {(x2 - x1) / w:.6f} {(y2 - y1) / h:.6f}")
        return lines


def keypair():
    """The reference issuer keypair, or None if `issuer/cli.py init` has not run.

    Imported inside the function on purpose: `issuer/` must never appear in an
    import graph reachable from `api/`, and `tests/test_contracts.py` checks it.
    """
    if not KEY_PATH.exists():
        return None
    from issuer.sign import Keypair
    return Keypair.load(ISSUER_DIR)


def build(doc_type: str, *, seed: int = 0, sign: bool = False,
          who: Identity | None = None) -> GeneratedDoc:
    """One document. `sign=True` mints a real signature over its payload."""
    if doc_type not in DOC_TYPES:
        raise ValueError(f"unknown document type {doc_type!r}")

    who = who or build_identity(seed)
    payload = who.payload(doc_type)

    envelope = qr_png = None
    if sign:
        pair = keypair()
        if pair is None:
            raise FileNotFoundError(
                f"no issuer key at {KEY_PATH}. Run: python -m issuer.cli init")
        from issuer.qr import encode_bytes
        from issuer.sign import sign as sign_payload
        envelope = sign_payload(payload, pair)
        qr_png = encode_bytes(envelope, scale=3, border=2)

    drawn = _render.render(doc_type, who, seed=seed, signed_qr=qr_png)
    # PIL is RGB; everything downstream of here is OpenCV, which is BGR.
    image = np.array(drawn.image)[:, :, ::-1].copy()

    return GeneratedDoc(doc_type=doc_type, identity=who, image=image,
                        labels=drawn.labels, values=drawn.values,
                        payload=payload, envelope=envelope)


def session(seed: int = 0, *, disagree_on: str | None = None,
            types: tuple[str, ...] = ("aadhaar", "pan")) -> list[GeneratedDoc]:
    """Several documents held by one person - Scene 3, as data.

    With `disagree_on` set, the *later* documents print a different value for
    that field while the first keeps the true one. Sign the first and Layer D
    has exactly the case the headline demo needs: a cryptographically proven
    date of birth, and a second document that contradicts it.

    The disagreement is introduced by editing the identity the later cards are
    drawn from, not by editing pixels, so the printed value and the value the
    card *means* stay consistent with each other. A forger who alters a card
    leaves the two disagreeing; that is a different mutation, and
    `data/tools/mutate.py` does it.
    """
    import copy

    truthful = build_identity(seed)
    docs = [build(types[0], seed=seed, sign=True, who=truthful)]

    other = truthful
    if disagree_on:
        other = copy.deepcopy(truthful)
        if disagree_on == "dob":
            year = int(truthful.dob[:4]) + 2
            other.dob = f"{year}{truthful.dob[4:]}"
        elif disagree_on == "name":
            other.surname = truthful.surname[::-1]
        else:
            setattr(other, disagree_on, f"{getattr(truthful, disagree_on)}X")

    for offset, kind in enumerate(types[1:], start=1):
        docs.append(build(kind, seed=seed + offset * 1000, who=other))
    return docs
