"""Build the SIH 26188 submission document. BUILD TIME ONLY.

    python docs/build_docx.py

Figures come from docs/figures/*.png, regenerated by the scripts beside them.
Every number in here is measured and traceable to a file in the repo; where a
thing is unmeasured it says unmeasured rather than nothing.
"""
from pathlib import Path
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.section import WD_SECTION
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

ROOT = Path(__file__).resolve().parent
FIG = ROOT / "figures"

INTAGLIO = RGBColor(0x3A, 0x2E, 0x45)
IRIS_INK = RGBColor(0x6E, 0x5C, 0x7A)
CLEAR    = RGBColor(0x1F, 0x5D, 0x4C)
DETAIN   = RGBColor(0xA3, 0x12, 0x3A)
SECOND   = RGBColor(0x8A, 0x6A, 0x0F)

doc = Document()

# ---------------------------------------------------------------- page setup
for s in doc.sections:
    s.left_margin = s.right_margin = Inches(0.8)
    s.top_margin = s.bottom_margin = Inches(0.75)

def style(name, size, *, bold=False, color=INTAGLIO, font="Calibri"):
    st = doc.styles[name]
    st.font.name = font; st.font.size = Pt(size)
    st.font.bold = bold; st.font.color.rgb = color
    st.element.rPr.rFonts.set(qn("w:eastAsia"), font)
    return st

style("Normal", 10.5)
doc.styles["Normal"].paragraph_format.space_after = Pt(6)
doc.styles["Normal"].paragraph_format.line_spacing = 1.15

def shade(cell, hexcolor):
    tcPr = cell._tc.get_or_add_tcPr()
    el = OxmlElement("w:shd"); el.set(qn("w:val"), "clear")
    el.set(qn("w:fill"), hexcolor); tcPr.append(el)

def para(text="", *, size=10.5, bold=False, italic=False, color=INTAGLIO,
         align=None, space_before=0, space_after=6, indent=0):
    p = doc.add_paragraph()
    r = p.add_run(text); r.bold = bold; r.italic = italic
    r.font.size = Pt(size); r.font.color.rgb = color; r.font.name = "Calibri"
    if align: p.alignment = align
    p.paragraph_format.space_before = Pt(space_before)
    p.paragraph_format.space_after = Pt(space_after)
    if indent: p.paragraph_format.left_indent = Inches(indent)
    return p

def rich(parts, *, size=10.5, space_after=6, indent=0):
    p = doc.add_paragraph()
    for text, bold, color in parts:
        r = p.add_run(text); r.bold = bold
        r.font.size = Pt(size); r.font.color.rgb = color; r.font.name = "Calibri"
    p.paragraph_format.space_after = Pt(space_after)
    if indent: p.paragraph_format.left_indent = Inches(indent)
    return p

def h1(text, num=None):
    doc.add_page_break()
    p = doc.add_paragraph()
    if num:
        r = p.add_run(f"{num}   "); r.bold = True; r.font.size = Pt(20)
        r.font.color.rgb = IRIS_INK; r.font.name = "Calibri"
    r = p.add_run(text); r.bold = True; r.font.size = Pt(20)
    r.font.color.rgb = INTAGLIO; r.font.name = "Calibri"
    p.paragraph_format.space_after = Pt(2)
    bar = doc.add_paragraph(); bar.paragraph_format.space_after = Pt(10)
    pPr = bar._p.get_or_add_pPr(); pbdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single"); bottom.set(qn("w:sz"), "12")
    bottom.set(qn("w:color"), "B39BBE"); pbdr.append(bottom); pPr.append(pbdr)

def h2(text, color=INTAGLIO):
    p = doc.add_paragraph()
    r = p.add_run(text); r.bold = True; r.font.size = Pt(13)
    r.font.color.rgb = color; r.font.name = "Calibri"
    p.paragraph_format.space_before = Pt(12); p.paragraph_format.space_after = Pt(4)

def h3(text, color=IRIS_INK):
    p = doc.add_paragraph()
    r = p.add_run(text.upper()); r.bold = True; r.font.size = Pt(9.5)
    r.font.color.rgb = color; r.font.name = "Calibri"
    p.paragraph_format.space_before = Pt(10); p.paragraph_format.space_after = Pt(3)

def bullets(items, *, size=10.5, indent=0.18):
    for it in items:
        p = doc.add_paragraph(style="List Bullet")
        if isinstance(it, tuple):
            head, rest = it
            r = p.add_run(head); r.bold = True
            r.font.size = Pt(size); r.font.color.rgb = INTAGLIO; r.font.name = "Calibri"
            r = p.add_run(rest)
        else:
            r = p.add_run(it)
        r.font.size = Pt(size); r.font.color.rgb = INTAGLIO; r.font.name = "Calibri"
        p.paragraph_format.left_indent = Inches(indent + 0.18)
        p.paragraph_format.space_after = Pt(3)

def figure(name, caption_text, width=6.9):
    doc.add_picture(str(FIG / name), width=Inches(width))
    doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.paragraphs[-1].paragraph_format.space_before = Pt(6)
    doc.paragraphs[-1].paragraph_format.space_after = Pt(2)
    para(caption_text, size=8.5, italic=True, color=IRIS_INK,
         align=WD_ALIGN_PARAGRAPH.CENTER, space_after=10)

def table(headers, rows, widths=None, *, size=9.5, head_fill="3A2E45",
          zebra="F6EEF7"):
    t = doc.add_table(rows=1, cols=len(headers))
    t.style = "Table Grid"; t.alignment = WD_TABLE_ALIGNMENT.CENTER
    hdr = t.rows[0].cells
    for i, htxt in enumerate(headers):
        shade(hdr[i], head_fill)
        p = hdr[i].paragraphs[0]; p.paragraph_format.space_after = Pt(2)
        r = p.add_run(htxt); r.bold = True; r.font.size = Pt(size)
        r.font.color.rgb = RGBColor(0xFF, 0xF2, 0xCF); r.font.name = "Calibri"
    for n, row in enumerate(rows):
        cells = t.add_row().cells
        for i, val in enumerate(row):
            if zebra and n % 2 == 1: shade(cells[i], zebra)
            p = cells[i].paragraphs[0]; p.paragraph_format.space_after = Pt(2)
            bold = val.startswith("**") and val.endswith("**")
            txt = val.strip("*")
            r = p.add_run(txt); r.bold = bold
            r.font.size = Pt(size); r.font.color.rgb = INTAGLIO; r.font.name = "Calibri"
    if widths:
        for row in t.rows:
            for i, w in enumerate(widths):
                row.cells[i].width = Inches(w)
    doc.add_paragraph().paragraph_format.space_after = Pt(4)
    return t

def callout(title, body, fill="FDF6E3", edge=SECOND):
    t = doc.add_table(rows=1, cols=1); t.style = "Table Grid"
    c = t.rows[0].cells[0]; shade(c, fill)
    p = c.paragraphs[0]; p.paragraph_format.space_after = Pt(2)
    r = p.add_run(title); r.bold = True; r.font.size = Pt(10)
    r.font.color.rgb = edge; r.font.name = "Calibri"
    p2 = c.add_paragraph(); r = p2.add_run(body)
    r.font.size = Pt(9.5); r.font.color.rgb = INTAGLIO; r.font.name = "Calibri"
    p2.paragraph_format.space_after = Pt(2)
    doc.add_paragraph().paragraph_format.space_after = Pt(4)

print("scaffold ready")

# ============================================================== COVER
para("SMART INDIA HACKATHON 2026", size=10, bold=True, color=IRIS_INK,
     align=WD_ALIGN_PARAGRAPH.CENTER, space_before=70, space_after=2)
para("Problem Statement 26188", size=10, color=IRIS_INK,
     align=WD_ALIGN_PARAGRAPH.CENTER, space_after=26)

p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = p.add_run("Offline Identity Document\nScreening for Border Checkpoints")
r.bold = True; r.font.size = Pt(28); r.font.color.rgb = INTAGLIO; r.font.name = "Calibri"
p.paragraph_format.space_after = Pt(10)

para("Three levels of certainty. One second. No network. No GPU.",
     size=13, italic=True, color=IRIS_INK, align=WD_ALIGN_PARAGRAPH.CENTER,
     space_after=30)

table(["", ""],
      [["Problem Statement ID", "**26188**"],
       ["Ministry / Organisation", "Ministry of Home Affairs — Sashastra Seema Bal (SSB)"],
       ["Category", "Software"],
       ["Theme", "Blockchain & Cybersecurity / Smart Automation"],
       ["Deployment context", "Land border Integrated Check Posts (Raxaul, Sunauli, Jogbani, Panitanki)"],
       ["Document types covered", "Aadhaar · PAN · Passport · Voter ID (EPIC) · Driving Licence · Visa"]],
      widths=[2.0, 4.9], size=10)

para("A border officer places a document under a scanner and points a camera at the "
     "person holding it. In about one second the system returns a colour-coded verdict "
     "with a list of specific, checkable reasons — and tells the officer how certain "
     "each reason is. It runs entirely offline on a commodity CPU.",
     size=11, align=WD_ALIGN_PARAGRAPH.CENTER, space_before=20)

# ============================================================== 1 IDEA
h1("Idea and Proposed Solution", "1")

h2("The problem, as it exists at the counter")
para("Land border check posts process thousands of identity documents a day. Verification "
     "today is manual, and the constraints are unusually harsh:")
bullets([
    ("Judgement under queue pressure. ", "An officer has seconds per document. A reprinted date or a swapped photograph does not survive scrutiny — it survives the absence of scrutiny."),
    ("No two officers agree. ", "There is no shared standard. Experience is the only check, and it leaves with the officer."),
    ("No connectivity and no GPU. ", "A border post at Raxaul has neither. Every cloud OCR service, hosted model and central database is unavailable by construction, not by preference."),
    ("Four of six Indian identity documents carry no cryptographic integrity. ", "Aadhaar, PAN, Voter ID and Driving Licence cannot be verified against an issuer at the counter. There is nothing to check a signature against."),
    ("Decisions are not reconstructable. ", "When a verdict is challenged months later, nothing recorded says why it was reached."),
])

h2("Our idea")
para("A screening system that reads a document, validates it at three explicit levels of "
     "certainty, checks it for tampering, matches the holder's face, and gives the officer "
     "a colour-coded verdict with reasons they can re-check by eye. The whole of it fits in "
     "one process on an eight-core CPU with the network cable physically removed.")

callout("The single idea the whole system is built on",
        "Not every check is equally trustworthy, and the officer must be told which is which. "
        "A signature that verifies is certain. A check digit is deterministic. A tamper "
        "heuristic is a guess. Presenting all three as one number is what makes existing "
        "systems un-auditable — and it is the thing we refuse to do.")

figure("fig1_problem_and_idea.png",
       "Figure 1 — The problem at a border check post, and what the system changes.")

h2("System block diagram")
para("Nine layers in a single process. Tier 1 runs on every document; Tier 2 fires only when "
     "the risk gate escalates, which is roughly one document in seven.")
figure("fig2_block_architecture.png",
       "Figure 2 — System block diagram. Nine layers, one process, no network.")

h2("What makes this different from an OCR pipeline")
bullets([
    ("Trust classes are first-class. ", "Every signal carries the class of evidence it came from, and the console shows it. A cryptographic pass and a tamper heuristic never appear as the same kind of statement."),
    ("An unreadable document is never cleared. ", "Coverage is the fraction of applicable check weight that actually produced an answer. Below 0.70 the verdict is AMBER regardless of score. A blurred photograph produces \"re-capture required\", never GREEN."),
    ("Evidence is written for a human. ", "\"MRZ date of birth 1991-08-04 does not match printed 1998-11-02\" — not \"viz_mrz_dob_mismatch=True\"."),
    ("The system assists; it does not decide. ", "The officer sees the margin from threshold and the operating point, and makes the call."),
])

h2("The reference issuer, stated plainly")
para("Four of the six documents have no cryptographic integrity in reality, and we hold no "
     "government keys — no UIDAI certificate, no Passport Seva endpoint, no government API of "
     "any kind. We therefore built a reference issuer that signs documents with Ed25519 and "
     "deposits its public key in a trust anchor store during setup. The verification path is "
     "real and complete; swapping in a genuine issuer key changes no code. The console renders "
     "a disclosure string on every such verification so it can never be mistaken for a "
     "government one.")

# ============================================================== 2 TECHNICAL APPROACH
h1("Technical Approach", "2")

h2("Decision flow")
para("The order of the verdict logic is fixed and is not negotiable: a hard failure wins "
     "outright without scoring, then the coverage floor, then the weighted sum. Reversing any "
     "two of these produces a system that clears documents it should not.")
figure("fig3_flowchart.png",
       "Figure 3 - Decision flow. The order is fixed: hard fail, then coverage, then score.", width=5.5)

h2("The three trust classes")
figure("fig4_trust_classes.png",
       "Figure 4 - Three trust classes. Every verdict says which one it came from.")

h2("The contract every module obeys")
para("Modules return a list of Signals and nothing else. No images, no dictionaries, no "
     "exceptions used as control flow. A Signal carries a stable dotted id, a verdict, a trust "
     "class, a confidence, an anchor, an officer-readable evidence string and its own latency.")
table(["Field", "Meaning"],
      [["id", "Stable dotted string, registered in CONTRACTS.md section 1"],
       ["verdict", "pass / fail / inconclusive / not_applicable - four different things"],
       ["trust_class", "cryptographic / arithmetic / probabilistic"],
       ["confidence", "Certainty of the check, not the score of the document"],
       ["anchor", "What the signal is about: document, or field:dob"],
       ["evidence", "A sentence a border officer reads and acts on"],
       ["latency_ms", "Measured, per signal. The budget is a requirement, not a hope"]],
      widths=[1.3, 5.6])

EM = "—"; MID = "·"; ARR = "→"; NE = "≠"; SEC = "§"

callout("Four verdicts, not two " + EM + " the safety property that matters most",
        "inconclusive is not pass, and not_applicable is not inconclusive. Aadhaar has no MRZ, "
        "so the MRZ check is not_applicable and leaves the coverage denominator. An MRZ too "
        "blurred to read is inconclusive and counts against coverage. Collapsing these two is "
        "exactly how a blurry photograph produces a GREEN verdict.",
        fill="F6EEF7", edge=IRIS_INK)

h2("Weights live in the profile, never in the module")
para("A signal does not know its own importance. Six YAML profiles " + EM + " one per document "
     "type " + EM + " declare which fields exist, which checks apply, what each check is worth, "
     "which failures are fatal, and the disclosure string. A module that forgot to flag a hard "
     "failure still hard-fails if the profile says the id does. This is what makes the verdict "
     "consistent between officers and re-scorable months later.")

h2("Two tiers, one budget")
table(["", "Runs on", "Contains", "Budget"],
      [["**Tier 1**", "Every document",
        "Extraction, validation A-F, cheap tampering, 1:1 face, passive liveness", "< 1 s"],
       ["**Tier 2**", "~15 %, on escalation",
        "Deep forensics (SRM, double-JPEG), 1:N gallery search", "Additional"]],
      widths=[0.9, 1.5, 3.4, 1.1])

h1("Feasibility and Viability", "3")

h2("Feasibility " + EM + " what is already working")
para("This is not a proposal. The deterministic and cryptographic path is built, measured and "
     "under test today.")
table(["Evidence of feasibility", "Status"],
      [["Automated test suite",
        "**374 passing, 7 skipped** " + EM + " property tests on fusion, ICAO 9303 published examples on the MRZ parser"],
       ["Officer console",
        "**34 tests, 4/4 build gates** " + EM + " typecheck, tests, production build, offline audit of built assets"],
       ["Offline guarantee",
        "Enforced by a test: any module importing a network-capable package fails the build"],
       ["Face 1:1 separation",
        "Genuine median **0.866**, impostor max **0.229** on generated documents"],
       ["Passive liveness",
        "Live median **0.973** " + MID + " printed photo **0.001** " + MID + " phone screen **0.001**"],
       ["Watchlist",
        "**8,256** OFAC SDN + UN Consolidated entries, lookup p95 **0.11 ms**"],
       ["Tamper detection",
        "Copy-move false positives driven **35 % " + ARR + " 5.0 %**; ghost portrait **0 %** FP, **100 %** of portrait swaps caught"],
       ["Containerisation",
        "docker compose up runs the whole system; models are baked into the image"]],
      widths=[2.2, 4.7])

h2("Challenges, and what we actually did about each")
table(["Challenge", "How it is addressed"],
      [["**No government keys or APIs**",
        "A reference issuer signs with Ed25519 and deposits its public key in the trust anchor "
        "store. The verification path is real; a genuine key changes no code. The UI discloses it."],
       ["**No real forged documents exist to train on**",
        "A synthetic generator produces all six types with checksum-valid numbers, plus a "
        "mutation family (photo swap, DOB splice, VIZ/MRZ desync, retype, copy-move) with "
        "ground-truth masks. We train on one mutation family and test on a different one."],
       ["**CPU-only, under one second**",
        "Every model is ONNX int8. Sessions are loaded once at startup; nothing constructs a "
        "session inside a request handler. Latency is measured per signal, not assumed."],
       ["**Clean renders are not real scans**",
        "A print-and-rescan pass is treated as mandatory. A model trained only on clean renders "
        "falls apart on a real scanner, and the documentation says so."],
       ["**Face thresholds are domain-specific**",
        "Published benchmarks are live-to-live. A passport photo is printed, screened and up to "
        "ten years old. We calibrate on our own document-to-live captures rather than borrowing "
        "a number that is wrong in the direction that admits impostors."],
       ["**Demographic bias is real and consequential**",
        "A bias harness is written and runs against FairFace or RFW. Until that data is on disk "
        "the disparity is recorded as unmeasured, which is a very different claim from small."]],
      widths=[1.9, 5.0])

h2("Our strategic approach")
bullets([
    ("Frozen contracts first. ",
     "Signal, ScreeningContext, Finding and the profile schema were frozen in week 0 so four "
     "workstreams could build in parallel against them."),
    ("Deterministic before probabilistic. ",
     "Checksums, signatures and date logic need no training data and no GPU, and they are the "
     "most defensible half of the system. They were built first and they work."),
    ("Measure, then claim. ",
     "Every number in this document is traceable to a script in the repository. Where something "
     "is unmeasured, it says unmeasured."),
    ("A published cut list. ",
     "Five features are ranked for removal under time pressure, each with a defensible answer. "
     "Knowing what to drop is what keeps the core intact."),
    ("Adversarial self-review. ",
     "The system is audited against its own assumptions. Four defects were found this way, "
     "including two where it cleared a document it should not have. Each is documented with "
     "its measurement."),
])

h2("Solution benefits")
figure("fig5_benefits.png",
       "Figure 5 " + EM + " What the system gives back, and why each one holds at a real check post.")

h2("Target audience and impact")
figure("fig6_impact.png",
       "Figure 6 " + EM + " Target audiences and the concrete change each one sees.")

h2("Scalability and the path to deployment")
bullets([
    ("Horizontal by construction. ",
     "One self-contained container per counter. There is no shared database on the critical "
     "path; the store is SQLite on the local disk."),
    ("A network of posts is a configuration change. ",
     "Setting SCREENING_POST_ID activates cross-post transit checking against a coordinate "
     "table. A single post correctly reports not_applicable."),
    ("New document types are YAML. ",
     "A new profile maps onto the existing 22-class field ontology. No new model is required."),
    ("Real issuer keys drop straight in. ",
     "The trust anchor store is keyed by issuer id. Production keys replace reference keys with "
     "no code change."),
])

h1("Technical Pipeline", "4")

para("Nine stages. Each one has exactly one job and exactly one kind of output. The rule that "
     "keeps the whole thing honest is that a module returns a list of Signals and nothing "
     "else " + EM + " no images, no dictionaries, no exceptions used as control flow.")
figure("fig7_pipeline.png",
       "Figure 7 " + EM + " Technical pipeline. Each stage's only output is a list of Signals.",
       width=6.6)

h2("Stage by stage")

h3("1-3  Capture, decode, route")
para("The image is decoded exactly once into ctx.image and no module ever re-reads the bytes or "
     "re-decodes the file. A module needing another resolution derives it. The officer selects "
     "the document type at the counter, so the profile is known before any model runs " + EM +
     " which is also why no document-type classifier is needed.")

h3("4  Extraction")
para("A single YOLOv11s field detector covers all six document types against a shared 22-class "
     "ontology " + EM + " one warm session rather than six, and shared classes generalise "
     "better. Located fields are read by PP-OCRv4 on crops only. Three parse paths run: the "
     "machine-readable zone, the QR payload, and printed text.")
bullets([
    ("The MRZ needs no detector. ",
     "ICAO 9303 fixes it at the foot of the data page, so it is read from its standard position. "
     "Its own five check digits then test the read before the strip is stored " + EM + " a "
     "failed check digit on an untargeted read is far more likely a misread than a forgery."),
    ("Florence-2 is the fallback, not a second opinion. ",
     "It fires at most once per document with an eight-second ceiling, and it stands down "
     "entirely once the MRZ has been read, because a verified MRZ already carries those fields "
     "with arithmetic backing."),
    ("Every fallback read passes a checksum ratifier. ",
     "A VLM transcription that cannot be validated does not enter the field set as fact."),
])

h3("5  Validation, layers A to F")
table(["Layer", "What it establishes"],
      [["**A**", "Ed25519 signature, trust anchors, Verhoeff (Aadhaar), PAN structure, EPIC format, ICAO check digits"],
       ["**B**", "ISO 3166 country codes, field lengths, character sets, date formats"],
       ["**C**", "Date ordering, validity period, age consistency, and the VIZ/MRZ cross-check"],
       ["**D**", "Trust propagation: a verified signature validates printed fields, within a document and across a session"],
       ["**E**", "Watchlist against local OFAC SDN and UN Consolidated tables, with phonetic near-matching"],
       ["**F**", "Temporal: prior crossings, and impossible transit between posts"]],
      widths=[0.7, 6.2])

callout("The highest-value tamper signal in the system",
        "A forger alters the printed date of birth and leaves the machine-readable zone alone. "
        "The two then disagree. That is not a model output " + EM + " it is two fields being "
        "different, and the officer can read both. It requires no training data and it is the "
        "one check we would never cut.",
        fill="E9F3EF", edge=CLEAR)

h3("6  Tampering")
para("Two tracks, both classical and individually explainable. The digital track covers "
     "copy-move (ORB feature matching with compactness and correlation guards), error-level "
     "analysis, noise residual, double-JPEG and EXIF provenance. The physical track covers "
     "OCR-B conformance, glyph-height consistency, guilloche line-work, ghost portrait presence "
     "and layout geometry. No training data is required for any of it.")

h3("7  Face")
para("SCRFD detection, ArcFace 512-d embedding, MiniFASNet passive liveness, all ONNX on CPU. "
     "Quality gates run before matching, with a deliberately looser blur threshold for the "
     "printed document photograph than for the live camera frame, because printed photographs "
     "are naturally softer.")

h3("8-9  Risk gate and fusion")
para("The gate escalates roughly one document in seven to Tier 2. Fusion then groups correlated "
     "signals into findings by anchor so that three readings of one artefact do not inflate the "
     "score three times, applies trust-class precedence, checks the coverage floor, and produces "
     "the evidence cards the officer actually reads.")

h2("Measured performance")
para("Measured on the development machine (16 logical cores, ONNX Runtime pinned to 4 intra-op "
     "threads), over generated documents with warm sessions. p95 rather than mean, because a "
     "checkpoint queue is served by its slow tail.")
table(["Document", "p50", "p95", "Reading path taken"],
      [["Passport", "**1,352 ms**", "7,073 ms", "MRZ read and check-digit verified, 28 of 30"],
       ["Aadhaar", "6,596 ms", "7,924 ms", "VLM fallback, 12 of 12"],
       ["PAN", "6,006 ms", "6,355 ms", "VLM fallback, 12 of 12"],
       ["Face module alone", "**103 ms**", "143 ms", "Within its 320 ms budget"]],
      widths=[1.7, 1.2, 1.2, 2.8])

callout("Stated plainly, because it will be asked",
        "Against the 1,020 ms budget this does not yet fit. The figure is bimodal, not noisy: "
        "the field detector is still training on an external GPU, so documents without a "
        "machine-readable zone fall through to the Florence-2 fallback and spend seconds there. "
        "The passport number is therefore a floor and the Aadhaar and PAN numbers a ceiling. "
        "We expect the detector to remove the fallback on the common path, and we have not "
        "measured that, so we do not claim it.",
        fill="FBE9EE", edge=DETAIN)

h2("Memory")
table(["State", "Resident"],
      [["Warm, idle (all startup models loaded)", "**154 MB**"],
       ["Working, machine-readable-zone path", "**185 MB**"],
       ["Working, Florence-2 fallback resident", "**1,556 MB**"]],
      widths=[4.6, 2.3])
para("The Florence-2 figure is a real constraint on checkpoint hardware and is recorded rather "
     "than hidden. It is a consequence of the fallback firing on every document that has no "
     "machine-readable zone, which is a temporary condition.", size=9.5, color=IRIS_INK)

h1("Research and References", "5")

h2("Standards")
table(["Reference", "Use in this system"],
      [["**ICAO Doc 9303**, Machine Readable Travel Documents, Parts 3 and 4",
        "TD3 layout and the five check digits. The one genuine external standard the system "
        "anchors on; the parser is tested against the specification's own published examples."],
       ["**ISO/IEC 7064**, check character systems",
        "Check-digit methodology underlying the identity-number validators"],
       ["**ISO 3166-1 alpha-3**, country codes",
        "Nationality validation, plus the ICAO supplementary codes that ISO does not define "
        "(D, GBD, XXA, XXX, RKS, UNO)"],
       ["**Verhoeff algorithm** (J. Verhoeff, 1969)",
        "Aadhaar number checksum"],
       ["**RFC 8032**, Edwards-Curve Digital Signature Algorithm (EdDSA)",
        "Ed25519 signing and verification in the reference issuer"],
       ["**NIST FRVT**, Face Recognition Vendor Test, demographic effects",
        "The basis for treating demographic disparity as a compliance item rather than a "
        "nice-to-have"]],
      widths=[2.5, 4.4])

h2("Models and methods")
table(["Reference", "Use in this system"],
      [["**SCRFD** " + EM + " Sample and Computation Redistribution for Efficient Face Detection",
        "Face detection (InsightFace buffalo_sc), ONNX on CPU"],
       ["**ArcFace** " + EM + " Additive Angular Margin Loss for Deep Face Recognition",
        "512-d face embedding and cosine comparison"],
       ["**MiniFASNet** / Silent-Face-Anti-Spoofing (Apache-2.0)",
        "Passive liveness. Converted to ONNX at build time; only the ONNX enters the image"],
       ["**PP-OCRv4** (PaddleOCR), served through RapidOCR",
        "Text recognition on field crops, English and Devanagari"],
       ["**YOLOv11** (Ultralytics)",
        "Single 22-class field detector shared across all six document types"],
       ["**Florence-2** (Microsoft)",
        "Vision-language fallback reader, OCR-with-region, eight-second ceiling"],
       ["**Error Level Analysis**; **SRM** noise residual; **ORB** keypoints",
        "Classical digital tamper forensics, no training data required"]],
      widths=[2.5, 4.4])

h2("Data sources and provenance")
table(["Source", "Licence", "Use"],
      [["Synthetic generator (this project)", "Ours",
        "**Every document screened, tested and demonstrated.** Checksum-valid numbers, no real ID anywhere"],
       ["SFHQ, Synthetic Faces High Quality", "CC0 Public Domain",
        "Face pool for generated documents. StyleGAN output; no real person"],
       ["OFAC SDN list", "Public government data", "Watchlist seed (8,256 entries with UN)"],
       ["UN Consolidated List", "Public government data", "Watchlist seed"],
       ["Roboflow Universe field datasets", "CC BY 4.0 / MIT / Public Domain",
        "Field-detector training corpus. Gitignored, never redistributed"],
       ["FairFace / RFW", "Research use",
        "Bias evaluation harness. **Not yet run** " + EM + " disparity is recorded as unmeasured"]],
      widths=[2.2, 1.7, 3.0])

callout("The provenance answer, in one sentence",
        "Every identity document this system has ever screened, tested or demonstrated on is "
        "synthetic, generated from published specimen layouts with checksum-valid numbers. No "
        "real Aadhaar, PAN, passport, Voter ID or Driving Licence image or number exists in any "
        "dataset, fixture, test or commit. The only real biometric anywhere is team face images "
        "for threshold calibration, held under written consent and never committed.",
        fill="E9F3EF", edge=CLEAR)

h1("Technology Stack", "6")

figure("fig8_techstack.png",
       "Figure 8 " + EM + " Technology stack. Every runtime dependency installs offline from a "
       "locked file.")

h2("Detail")
table(["Layer", "Technology", "Why this one"],
      [["**Officer console**", "React 19, TypeScript, Vite 8, Tailwind CSS 4, Zustand",
        "Static bundle, no runtime fetch. A build gate audits the output for external resources"],
       ["**Transport**", "FastAPI, Uvicorn, WebSocket",
        "Signals stream to the console as each stage completes, so the officer sees the first "
        "verdict before the last check finishes"],
       ["**Contracts**", "Pydantic, frozen dataclasses, YAML profiles",
        "One schema shared by four workstreams; changing it is a deliberate act"],
       ["**Inference**", "ONNX Runtime, CPU, int8 quantised",
        "No CUDA, no torch, no vLLM. A model that cannot run on CPU in under 2 s does not go in"],
       ["**Vision**", "OpenCV, NumPy",
        "Classical forensics need no training data and are individually explainable"],
       ["**Cryptography**", "cryptography (Ed25519)",
        "RFC 8032. The reference issuer is out-of-band tooling and is never importable from the API"],
       ["**Storage**", "SQLite",
        "One file per counter. Removes a network dependency from a system whose whole claim is "
        "that it has none"],
       ["**Build-time only**", "Ultralytics, PyTorch (CUDA), Faker, Pillow, paddle2onnx",
        "A separate environment. None of it enters the screening image"],
       ["**Packaging**", "Docker, docker-compose",
        "Models baked in at build. Nothing downloads at run time"]],
      widths=[1.4, 2.2, 3.3])

callout("Three environments that deliberately do not mix",
        "requirements.txt is the screening image: CPU, offline, torch-free. requirements-build.txt "
        "holds the generator and model fetchers. A separate training environment holds CUDA "
        "PyTorch. A test fails the build if anything in the screening path imports a package "
        "that can reach the network.",
        fill="F6EEF7", edge=IRIS_INK)

h1("Honest Limitations", "7")

para("Knowing the limits of a system buys more credibility with an evaluator than any single "
     "number. These are stated here rather than discovered in questioning.")

table(["Limitation", "Status and what closes it"],
      [["**Field detector not yet deployed**",
        "Training moved to an external GPU. Until the weights land, printed fields are read only "
        "by the fallback path, coverage stays below the floor on most documents, and the system "
        "correctly returns AMBER rather than clearing anything."],
       ["**Face threshold is not calibrated**",
        "The operating point is a placeholder and is flagged as uncalibrated in configuration. "
        "It needs roughly 500 document-to-live pairs from 30 to 50 people. The capture tooling, "
        "consent flow and calibration script are built and rehearsed against stand-in data."],
       ["**Demographic disparity is unmeasured**",
        "Not small " + EM + " unmeasured. The harness runs the moment FairFace or RFW is on "
        "disk. NIST FRVT found false-match differentials above an order of magnitude across "
        "algorithms, so this is a real gap and it is named as one."],
       ["**Latency misses the budget today**",
        "Measured and published above rather than omitted. Expected to improve when the detector "
        "replaces the fallback; unmeasured, so not claimed."],
       ["**Accuracy figures are on synthetic forgeries**",
        "Real forged passports are not obtainable, for obvious reasons. We report on our own "
        "generated set and label it as such, and we test on a different mutation family from "
        "the one we train on."],
       ["**Professional forgery would likely pass**",
        "Matched materials would defeat the physical checks. This is why the system assists "
        "rather than decides, and why the evidence list matters more than the score."]],
      widths=[2.1, 4.8])

callout("What we would say to an evaluator about all of this",
        "The deterministic and cryptographic half of the system is complete and you can watch "
        "it work. The reading path waits on one model that trains on a GPU we do not have in "
        "the room. Until it lands the system refuses to clear anything it cannot read " + EM +
        " which is the behaviour we want from it. An unreadable document is not a cleared "
        "document.",
        fill="FDF6E3", edge=SECOND)

h1("Team Pack " + EM + " Everything Needed to Build the Deck", "8")

para("This section exists so a teammate who has not read the code can build the presentation, "
     "answer questions and rehearse the demo without asking anyone.")

h2("The one sentence to memorise")
callout("The claim the whole pitch rests on",
        "We verify identity documents at three levels of certainty " + EM + " cryptographic, "
        "arithmetic and probabilistic " + EM + " and we tell the officer which level each "
        "verdict came from. It runs on a commodity CPU with the network cable unplugged.",
        fill="F6EEF7", edge=IRIS_INK)

h2("Suggested slide plan")
table(["#", "Slide", "Put on it", "Say this"],
      [["1", "Title", "Problem statement number, team name, the one sentence above",
        "Open with the constraint, not the technology: a border post has no internet and no GPU"],
       ["2", "The problem", "Figure 1 (left half)",
        "Seconds per document, no shared standard, no connectivity, nothing written down"],
       ["3", "Our idea", "Figure 1 (right half) or the whole figure",
        "Three levels of certainty, always labelled. The officer decides; we show why"],
       ["4", "Architecture", "Figure 2",
        "Nine layers, one process, two tiers. Tier 2 fires on ~15 % of documents"],
       ["5", "Trust classes", "Figure 4",
        "The core idea. A signature, a check digit and a heuristic are not the same statement"],
       ["6", "Decision flow", "Figure 3",
        "Hard fail, then coverage, then score. An unreadable document is never cleared"],
       ["7", "Technical pipeline", "Figure 7",
        "Every stage returns a list of Signals and nothing else"],
       ["8", "Feasibility", "The feasibility table from section 3",
        "374 tests passing. Lead with what is measured"],
       ["9", "Benefits", "Figure 5",
        "Six benefits, each tied to a constraint of the real environment"],
       ["10", "Impact", "Figure 6",
        "Four audiences: officer, commander, auditor, traveller"],
       ["11", "Tech stack", "Figure 8",
        "CPU-only ONNX, offline install, models baked into the image"],
       ["12", "Limitations", "The limitations table from section 7",
        "Volunteer the gaps. This buys more credibility than any number"],
       ["13", "References", "The three tables from section 5",
        "ICAO 9303 is the one real external standard we anchor on"]],
      widths=[0.3, 1.2, 2.0, 3.4], size=9)

h2("Numbers worth memorising")
table(["Number", "What it is"],
      [["**374 / 7**", "Python tests passing / skipped. Console: 34 tests, 4 of 4 build gates"],
       ["**0.866 vs 0.229**", "Face 1:1 genuine median vs impostor maximum on generated documents"],
       ["**0.973 / 0.001 / 0.001**", "Passive liveness: live face / printed photo / phone screen"],
       ["**8,256**", "Watchlist entries (OFAC SDN + UN Consolidated), lookup p95 0.11 ms"],
       ["**35 % " + ARR + " 5.0 %**", "Copy-move false-positive rate, driven down by three guards"],
       ["**0 % / 100 %**", "Ghost-portrait check: false positives / portrait swaps caught"],
       ["**154 MB**", "Warm idle memory. 185 MB working on the machine-readable-zone path"],
       ["**1,352 ms**", "Passport p50 latency today (a floor; the detector is not yet deployed)"],
       ["**0.70**", "Coverage floor. Below it the verdict is AMBER regardless of score"],
       ["**22**", "Field ontology classes, shared across all six document types"],
       ["**6**", "Document types: Aadhaar, PAN, Passport, Voter ID, Driving Licence, Visa"]],
      widths=[1.6, 5.3])

h2("Questions you will be asked, and the answers")
table(["Question", "Answer"],
      [["Those are your own signatures " + EM + " how is that verification?",
        "Correct, and we say so in the interface. Four of six Indian documents have no "
        "cryptographic integrity in reality. We demonstrate signed verification end to end and "
        "validated our path against ICAO 9303, which is real. A genuine issuer key changes no code."],
       ["Where did your training data come from?",
        "Every document is synthetic, generated from published specimen layouts with "
        "checksum-valid numbers. No real government ID is in any dataset, fixture or commit."],
       ["What is your accuracy?",
        "On our synthetic tamper set, with the specific numbers in section 3. We train on one "
        "mutation family and test on another, and we report both. Untested against professional "
        "forgery, which we cannot obtain."],
       ["What about bias in face recognition?",
        "Unmeasured, and that is different from small. The harness is written and runs the "
        "moment FairFace or RFW is on disk. NIST FRVT found differentials above an order of "
        "magnitude, which is why the officer decides and we show the margin from threshold."],
       ["Why not use a GPU?",
        "Border posts do not have one. Everything is ONNX int8 on CPU; the system is 154 MB warm."],
       ["Can it be fooled?",
        "Yes. Professional forgery with matched materials would likely pass the physical checks. "
        "That is why the system assists rather than decides, and why the evidence list matters "
        "more than the score."],
       ["Does this work on a scanned PDF?",
        "Yes, and that path enables the digital forensics track. At a live counter those are "
        "less useful because the scanner writes the file, which is why the physical track is primary."],
       ["Why is everything AMBER in your demo?",
        "Because the field detector is still training and the system will not clear a document "
        "it cannot read. That is the safety property working exactly as designed."]],
      widths=[2.2, 4.7], size=9)

h2("Where to find things in the repository")
table(["Question", "File"],
      [["What is this project, in domain terms?", "context/CONTEXT.md"],
       ["What are the frozen interfaces?", "context/CONTRACTS.md"],
       ["Why is this odd thing like this?", "context/DECISIONS.md (48 numbered decisions)"],
       ["What is done and what remains?", "context/PROGRESS.md"],
       ["How is the demo run?", "context/DEMO.md (script, checklist, rehearsal record)"],
       ["Where did the data come from?", "data/PROVENANCE.md and docs/PROVENANCE-SLIDE.md"],
       ["What are the measured tamper numbers?", "data/TAMPERING.md"],
       ["What are the measured face numbers?", "data/FACE.md"],
       ["How is the detector trained?", "MODEL-TRAINING.md"],
       ["How do I regenerate these figures?", "docs/figures/*.py, then docs/build_docx.py"]],
      widths=[3.0, 3.9])

h2("Rules a teammate must not get wrong on stage")
bullets([
    ("Never say the system decides. ", "It assists. The officer decides, and that is a design position, not modesty."),
    ("Never present a reference-issuer verification as a government one. ", "The disclosure string exists for exactly this reason and the console always renders it."),
    ("Never quote an accuracy number without saying it is on synthetic forgeries. ", "This is the question that will be probed hardest."),
    ("Never say bias is small. ", "It is unmeasured. Say unmeasured."),
    ("If asked something you do not know, say so. ", "The project's whole credibility rests on naming its limits. Guessing on stage undoes that in one sentence."),
])

out = ROOT / "SIH-26188-Idea-Submission.docx"
doc.save(str(out))
print("saved:", out)
print("paragraphs:", len(doc.paragraphs), " tables:", len(doc.tables))
